import {
  ArrowDown,
  Bell,
  Briefcase,
  Check,
  Clock,
  Close,
  Collection,
  Cpu,
  DataLine,
  Delete,
  Document,
  Download,
  Edit,
  Expand,
  Fold,
  FolderOpened,
  FullScreen,
  Grid,
  Hide,
  Histogram,
  HomeFilled,
  Key,
  List,
  Lock,
  MagicStick,
  Management,
  Menu,
  Monitor,
  Moon,
  More,
  Odometer,
  OfficeBuilding,
  Operation,
  Picture,
  PieChart,
  Plus,
  Postcard,
  Rank,
  Refresh,
  RefreshRight,
  Search,
  Setting,
  Sort,
  Sunny,
  SwitchButton,
  Tickets,
  Timer,
  Tools,
  TrendCharts,
  Upload,
  User,
  UserFilled,
  View,
  Warning,
} from '@element-plus/icons-vue'
import type { Component } from 'vue'

/**
 * 图标注册表：`sys_menu.icon` 里存的名字 → Element Plus 图标组件。
 *
 * 只登记用得到的图标（而不是全量注册），保证 tree-shaking 生效。
 * 名字保持 `icon-xxx` 形式，与 db/menu.php 中已有的配置兼容。
 */
export const ICON_MAP: Record<string, Component> = {
  'icon-settings': Setting,
  'icon-user': User,
  'icon-safe': Lock,
  'icon-menu': Menu,
  'icon-tree': OfficeBuilding,
  'icon-badge': Postcard,
  'icon-book': Collection,
  'icon-tool': Tools,
  'icon-file': Document,
  'icon-upload': FolderOpened,
  'icon-clock': Clock,
  'icon-code': Cpu,

  // 以下供设置面板 / 顶部栏等静态位置使用
  'icon-home': HomeFilled,
  'icon-briefcase': Briefcase,
  'icon-grid': Grid,
  'icon-list': List,
  'icon-monitor': Monitor,
  'icon-bell': Bell,
  'icon-operation': Operation,
  'icon-management': Management,
  'icon-magic': MagicStick,
  'icon-key': Key,
  'icon-timer': Timer,
  'icon-odometer': Odometer,
  'icon-dataline': DataLine,
  'icon-pie': PieChart,
  'icon-trend': TrendCharts,
  'icon-histogram': Histogram,
  'icon-tickets': Tickets,
  'icon-refresh': Refresh,
  'icon-refresh-right': RefreshRight,
  'icon-fold': Fold,
  'icon-expand': Expand,
  'icon-fullscreen': FullScreen,
  'icon-search': Search,
  'icon-plus': Plus,
  'icon-close': Close,
  'icon-moon': Moon,
  'icon-sunny': Sunny,
  'icon-logout': SwitchButton,
  'icon-arrow-down': ArrowDown,
  'icon-more': More,
  'icon-rank': Rank,
  'icon-sort': Sort,
  'icon-user-filled': UserFilled,
  'icon-edit': Edit,
  'icon-delete': Delete,
  'icon-download': Download,
  'icon-picture': Picture,
  'icon-check': Check,
  'icon-warning': Warning,
  'icon-view': View,
  'icon-hide': Hide,
  'icon-upload-filled': Upload,
}

/** 菜单图标候选（图标选择器用，排除纯功能性图标） */
export const MENU_ICON_OPTIONS: string[] = [
  'icon-settings', 'icon-user', 'icon-safe', 'icon-menu', 'icon-tree', 'icon-badge',
  'icon-book', 'icon-tool', 'icon-file', 'icon-upload', 'icon-clock', 'icon-code',
  'icon-home', 'icon-briefcase', 'icon-grid', 'icon-list', 'icon-monitor', 'icon-bell',
  'icon-operation', 'icon-management', 'icon-magic', 'icon-key', 'icon-timer',
  'icon-odometer', 'icon-dataline', 'icon-pie', 'icon-trend', 'icon-histogram',
  'icon-tickets', 'icon-picture', 'icon-download', 'icon-view',
]

/** 按名字取图标组件；找不到时回退到 Menu，避免渲染空白 */
export function resolveIcon(name?: string): Component {
  if (!name) {
    return Menu
  }
  return ICON_MAP[name] ?? ICON_MAP[`icon-${name}`] ?? Menu
}
